import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BarChart3, BriefcaseBusiness, CalendarDays, Download, GraduationCap, MapPin, RefreshCcw, Search, Users } from 'lucide-react';
import './styles.css';

const branches = ['Aarau','Baden','Basel','Bern','Biel','Delémont','Fribourg','Genf','Lausanne','Luzern','Locarno','Martigny','Mendrisio','Neuchâtel','Olten','Porrentruy','St. Gallen','Sargans','Schaan','Solothurn','Thun','Vevey','Winterthur','Yverdon','Zürich'].map((name,i)=>({id:`f${i+1}`,name}));
const persons = ['Sarah','Deborah','Joha','Tanja','Babs'].map((name,i)=>({id:`p${i+1}`,name}));
const vacancyTypes = ['Personalberater','Assistentin','Filialleiter'];
const candidateStages = ['Dossier','Interview','Probetag','Anstellungsprozess','Abgesagt'];
const coachingSteps = ['Startcoaching','C1','C2','C3','C4','C5'];
const stepStates = ['offen','geplant','erledigt'];

const startVacancies = [
  ['f4','Personalberater','p1',18,5,4,2,1,'2026-06-24','Zwei passende Profile in Abklärung.'],
  ['f25','Assistentin','p2',10,3,2,1,0,'2026-06-25','Termin Probetag offen.'],
  ['f3','Filialleiter','p3',4,2,1,0,0,'','Nächster Schritt fehlt.'],
  ['f9','Personalberater','p4',7,3,2,1,0,'2026-06-26','Interviewrunde läuft.'],
  ['f10','Assistentin','p5',0,0,0,0,0,'','Inserat prüfen, keine Dossiers.']
].map((v,i)=>({id:`v${i+1}`,branchId:v[0],type:v[1],recruiterId:v[2],dossiers:v[3],rejections:v[4],interviews:v[5],trialDays:v[6],hiring:v[7],nextStepDate:v[8],notes:v[9]}));
const startCandidates = [
  ['Lea Keller','f4','v1','p1','Interview','2026-06-24','Zweites Interview geplant.'],
  ['Marco Frei','f25','v2','p2','Probetag','2026-06-25','Probetag mit Filiale Zürich.'],
  ['Nora Meier','f3','v3','p3','Interview','','Entscheid ausstehend.'],
  ['Samira Huber','f9','v4','p4','Dossier','2026-06-26','Dossier wird geprüft.'],
  ['David Rossi','f10','v5','p5','Dossier','','Noch kein nächster Schritt.'],
  ['Jonas Wyss','f8','v1','p2','Abgesagt','','Profil passt nicht.']
].map((c,i)=>({id:`c${i+1}`,name:c[0],branchId:c[1],vacancyId:c[2],recruiterId:c[3],stage:c[4],nextStepDate:c[5],notes:c[6]}));
function coachings(values={}){return coachingSteps.reduce((a,s)=>{const v=values[s]||['offen','',''];a[s]={state:v[0],date:v[1],notes:v[2]||''};return a;},{});}
const startTrainees = [
  ['Anna Berger','f4','Personalberaterin','2026-06-03','p1','Start gut gelungen.',{Startcoaching:['erledigt','2026-06-05'],C1:['geplant','2026-06-24']}],
  ['Timo Graf','f25','Assistent','2026-06-10','p2','Nächster Termin geplant.',{Startcoaching:['erledigt','2026-06-12'],C1:['geplant','2026-06-26']}],
  ['Elin Sutter','f3','Filialleiterin','2026-05-20','p3','Mehr Begleitung nötig.',{Startcoaching:['erledigt','2026-05-22'],C1:['erledigt','2026-06-03'],C2:['offen','2026-06-16']}],
  ['Lina Weber','f10','Assistentin','2026-06-12','p5','Admin-Schulung offen.',{Startcoaching:['offen','']}]
].map((t,i)=>({id:`m${i+1}`,name:t[0],branchId:t[1],role:t[2],startDate:t[3],trainerId:t[4],notes:t[5],coachings:coachings(t[6])}));
const initialReport = {week:'2026-W25',comment:'Bern, Zürich, Basel, Lausanne und Luzern im Wochenfokus. Bitte fehlende nächste Schritte bei roten Einträgen nachführen.'};
const emptyVacancy = () => ({branchId:'f4',type:'Personalberater',recruiterId:'p1',dossiers:0,rejections:0,interviews:0,trialDays:0,hiring:0,nextStepDate:'',notes:''});
const emptyCandidate = () => ({name:'',branchId:'f4',vacancyId:'v1',recruiterId:'p1',stage:'Dossier',nextStepDate:'',notes:''});
const emptyTrainee = () => ({name:'',branchId:'f4',role:'Personalberater',startDate:'',trainerId:'p1',notes:'',coachings:coachings()});
const nameOf = (items,id) => items.find(x=>x.id===id)?.name || 'Nicht zugewiesen';
const isPast = d => d && new Date(`${d}T00:00:00`) < new Date(new Date().toDateString());
function vacancyStatus(v){ if(Number(v.dossiers)===0 || !v.nextStepDate) return 'red'; if(Number(v.hiring)>0) return 'green'; return 'yellow'; }
function candidateStatus(c){ if(c.stage==='Abgesagt' || c.notes.toLowerCase().includes('blockiert')) return 'red'; if(c.nextStepDate) return 'green'; return 'yellow'; }
function traineeStatus(t){ const s=Object.values(t.coachings||{}); if(s.some(x=>x.state!=='erledigt'&&(!x.date||isPast(x.date)))) return 'red'; if(s.some(x=>x.state==='offen'||x.state==='geplant')) return 'yellow'; return 'green'; }
function branchStatus(v,t){ if(v.some(x=>vacancyStatus(x)==='red')||t.some(x=>traineeStatus(x)==='red')) return 'red'; if(v.some(x=>vacancyStatus(x)==='yellow')||t.some(x=>traineeStatus(x)==='yellow')) return 'yellow'; return 'green'; }
function statusText(s){ return s==='green'?'Grün - im Plan':s==='yellow'?'Gelb - Aufmerksamkeit nötig':'Rot - kritisch'; }
function nextCoaching(t){ return coachingSteps.find(s=>t.coachings?.[s]?.state!=='erledigt') || 'C5'; }
function App(){
  const saved=JSON.parse(localStorage.getItem('hr-reporting-v3')||'null');
  const [vacancies,setVacancies]=useState(saved?.vacancies||startVacancies);
  const [candidates,setCandidates]=useState(saved?.candidates||startCandidates);
  const [trainees,setTrainees]=useState(saved?.trainees||startTrainees);
  const [report,setReport]=useState(saved?.report||initialReport);
  const [filters,setFilters]=useState({branchId:'all',status:'all',query:'',recruiterId:'all',trainerId:'all'});
  const [vf,setVf]=useState(emptyVacancy()); const [cf,setCf]=useState(emptyCandidate()); const [tf,setTf]=useState(emptyTrainee());
  useEffect(()=>localStorage.setItem('hr-reporting-v3',JSON.stringify({vacancies,candidates,trainees,report})),[vacancies,candidates,trainees,report]);
  const branchName=id=>nameOf(branches,id), personName=id=>nameOf(persons,id), vacancyName=id=>{const v=vacancies.find(x=>x.id===id); return v?`${v.type} (${branchName(v.branchId)})`:'Vakanz';};
  const visible=useMemo(()=>{const q=filters.query.toLowerCase(); const qok=arr=>!q||arr.join(' ').toLowerCase().includes(q); const sok=s=>filters.status==='all'||filters.status===s; return {
    vacancies:vacancies.filter(v=>(filters.branchId==='all'||v.branchId===filters.branchId)&&(filters.recruiterId==='all'||v.recruiterId===filters.recruiterId)&&sok(vacancyStatus(v))&&qok([v.type,branchName(v.branchId),personName(v.recruiterId),v.notes])),
    candidates:candidates.filter(c=>(filters.branchId==='all'||c.branchId===filters.branchId)&&(filters.recruiterId==='all'||c.recruiterId===filters.recruiterId)&&sok(candidateStatus(c))&&qok([c.name,branchName(c.branchId),vacancyName(c.vacancyId),personName(c.recruiterId),c.stage,c.notes])),
    trainees:trainees.filter(t=>(filters.branchId==='all'||t.branchId===filters.branchId)&&(filters.trainerId==='all'||t.trainerId===filters.trainerId)&&sok(traineeStatus(t))&&qok([t.name,t.role,branchName(t.branchId),personName(t.trainerId),t.notes]))
  };},[filters,vacancies,candidates,trainees]);
  const totals={branches:branches.length,vacancies:vacancies.length,dossiers:sum(vacancies,'dossiers'),rejections:sum(vacancies,'rejections'),active:sum(vacancies,'interviews')+sum(vacancies,'trialDays')+sum(vacancies,'hiring'),trainees:trainees.length};
  function addVacancy(e){e.preventDefault();setVacancies([{...vf,id:`v${Date.now()}`},...vacancies]);setVf(emptyVacancy());}
  function addCandidate(e){e.preventDefault();if(!cf.name)return;const v=vacancies.find(x=>x.id===cf.vacancyId);setCandidates([{...cf,id:`c${Date.now()}`,branchId:v?.branchId||cf.branchId,recruiterId:v?.recruiterId||cf.recruiterId},...candidates]);setCf(emptyCandidate());}
  function addTrainee(e){e.preventDefault();if(!tf.name)return;setTrainees([{...tf,id:`m${Date.now()}`},...trainees]);setTf(emptyTrainee());}
  function updateVacancy(id,k,v){setVacancies(vacancies.map(x=>x.id===id?{...x,[k]:['dossiers','rejections','interviews','trialDays','hiring'].includes(k)?Number(v):v}:x));}
  function updateCandidate(id,k,v){setCandidates(candidates.map(x=>x.id===id?{...x,[k]:v}:x));}
  function updateTrainee(id,k,v){setTrainees(trainees.map(x=>x.id===id?{...x,[k]:v}:x));}
  function updateCoaching(id,step,k,v){setTrainees(trainees.map(x=>x.id===id?{...x,coachings:{...x.coachings,[step]:{...x.coachings[step],[k]:v}}}:x));}
  function reset(){localStorage.removeItem('hr-reporting-v3');setVacancies(startVacancies);setCandidates(startCandidates);setTrainees(startTrainees);setReport(initialReport);}
  function exportCsv(){const rows=[['Typ','Filiale','Name/Vakanz','Verantwortliche Person','Status','Nächster Schritt','Dossiers','Absagen','Interviews','Probetage','Anstellungsprozess','Bemerkung'],...vacancies.map(v=>['Vakanz',branchName(v.branchId),v.type,personName(v.recruiterId),statusText(vacancyStatus(v)),v.nextStepDate,v.dossiers,v.rejections,v.interviews,v.trialDays,v.hiring,v.notes]),...candidates.map(c=>['Kandidat/Kandidatin',branchName(c.branchId),c.name,personName(c.recruiterId),statusText(candidateStatus(c)),c.nextStepDate,'','','','',c.stage,c.notes]),...trainees.map(t=>['Mitarbeiter/Mitarbeiterin in Ausbildung',branchName(t.branchId),t.name,personName(t.trainerId),statusText(traineeStatus(t)),nextCoaching(t),'','','','',t.role,t.notes])]; const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(';')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download=`rekrutierung-ausbildung-${report.week}.csv`; a.click();}
  return <main className="app-shell"><header className="topbar"><div><p className="eyebrow">Interner Prototyp</p><h1>Rekrutierung & Ausbildung Reporting</h1></div><div className="top-actions"><button className="ghost-button" onClick={reset}><RefreshCcw size={17}/> Demo zurücksetzen</button><button className="primary-button" onClick={exportCsv}><Download size={17}/> CSV Export</button></div></header><section className="toolbar"><Sel label="Filiale" value={filters.branchId} onChange={v=>setFilters({...filters,branchId:v})} opts={[['all','Alle Filialen'],...branches.map(x=>[x.id,x.name])]}/><Sel label="Status" value={filters.status} onChange={v=>setFilters({...filters,status:v})} opts={[['all','Alle Status'],['green','Grün'],['yellow','Gelb'],['red','Rot']]}/><Sel label="Rekrutierer / Rekrutiererin" value={filters.recruiterId} onChange={v=>setFilters({...filters,recruiterId:v})} opts={[['all','Alle Rekrutierer'],...persons.map(x=>[x.id,x.name])]}/><Sel label="Ausbildner / Ausbildnerin" value={filters.trainerId} onChange={v=>setFilters({...filters,trainerId:v})} opts={[['all','Alle Ausbildner'],...persons.map(x=>[x.id,x.name])]}/><label className="search-field"><span>Suche</span><div><Search size={17}/><input value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})} placeholder="Name, Filiale oder Vakanz"/></div></label></section><Legend/><Dashboard totals={totals} vacancies={vacancies} candidates={candidates} trainees={trainees} branchName={branchName} personName={personName}/><section className="content-grid"><Panel title="Rekrutierungspipeline" icon={<BriefcaseBusiness size={18}/>}><Recruiting items={visible.candidates} branchName={branchName} vacancyName={vacancyName} personName={personName} update={updateCandidate}/></Panel><Weekly report={report} setReport={setReport} totals={totals} vacancies={vacancies} trainees={trainees} personName={personName}/></section><Panel title="Ausbildungs- / Coachingpipeline" icon={<GraduationCap size={18}/>}><Coaching items={visible.trainees} branchName={branchName} personName={personName} update={updateTrainee} updateCoaching={updateCoaching}/></Panel><section className="content-grid wide-left"><Panel title="Vakanzen erfassen und bearbeiten" icon={<BriefcaseBusiness size={18}/>}><VacancyForm f={vf} setF={setVf} submit={addVacancy}/><VacancyTable items={visible.vacancies} update={updateVacancy} branchName={branchName} personName={personName}/></Panel><Panel title="Neue Personen erfassen" icon={<Users size={18}/>}><CandidateForm f={cf} setF={setCf} submit={addCandidate} vacancies={vacancies} branchName={branchName}/><TraineeForm f={tf} setF={setTf} submit={addTrainee}/></Panel></section><Panel title={`Filialübersicht ${branches.length} Filialen`} icon={<MapPin size={18}/>}><Branches vacancies={vacancies} trainees={trainees} filters={filters} personName={personName}/></Panel></main>;
}
function sum(a,k){return a.reduce((n,x)=>n+Number(x[k]||0),0)} function Sel({label,value,onChange,opts}){return <label><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{opts.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function S({s}){return <span className={`status-text ${s}`}><span className="status-dot"/>{statusText(s)}</span>} function Panel({title,icon,children}){return <section className="panel"><div className="panel-title">{icon}<h2>{title}</h2></div>{children}</section>}
function Legend(){return <section className="legend"><strong>Farblogik</strong><span><S s="green"/> im Plan / keine kritischen offenen Punkte</span><span><S s="yellow"/> Aufmerksamkeit nötig / Prozess läuft, aber nächste Schritte sind offen</span><span><S s="red"/> kritisch / zu wenig Bewerbungen, blockiert oder kein nächster Schritt</span></section>}
function Dashboard({totals,vacancies,candidates,trainees,personName}){return <section className="dashboard"><div className="kpi-grid"><Kpi icon={<MapPin size={22}/>} label="Filialen" value={totals.branches}/><Kpi icon={<BriefcaseBusiness size={22}/>} label="Offene Vakanzen" value={totals.vacancies} tone="red"/><Kpi icon={<BarChart3 size={22}/>} label="Dossiers" value={totals.dossiers}/><Kpi icon={<Users size={22}/>} label="Aktive Prozesse" value={totals.active} tone="yellow"/><Kpi icon={<GraduationCap size={22}/>} label="In Ausbildung" value={totals.trainees}/></div><div className="dashboard-lists"><Mini title="Offene Vakanzen nach Rekrutierer / Rekrutiererin" rows={countBy(vacancies,'recruiterId',personName)}/><Mini title="Dossiers pro Rekrutierer / Rekrutiererin" rows={sumBy(vacancies,'recruiterId','dossiers',personName)}/><Mini title="Kandidaten im Prozess pro Rekrutierer / Rekrutiererin" rows={countBy(candidates.filter(x=>candidateStatus(x)!=='red'),'recruiterId',personName)}/><Mini title="Mitarbeitende in Ausbildung pro Ausbildner / Ausbildnerin" rows={countBy(trainees,'trainerId',personName)}/><Mini title="Offene / überfällige Coachings pro Ausbildner / Ausbildnerin" rows={openCoachings(trainees,personName)}/></div></section>}
function Kpi({icon,label,value,tone=''}){return <article className={`kpi-tile ${tone}`}><div className="tile-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></article>} function Mini({title,rows}){return <article className="mini-stats"><h3>{title}</h3>{rows.length===0&&<p>Keine Einträge</p>}{rows.map(([l,v])=><div className="mini-stat-row" key={l}><span>{l}</span><strong>{v}</strong></div>)}</article>}
function Recruiting({items,branchName,vacancyName,personName,update}){return <div className="kanban">{candidateStages.map(st=>{const list=items.filter(x=>x.stage===st);return <div className="kanban-col" key={st}><div className="kanban-title">{st}<span>{list.length}</span></div>{list.map(c=>{const s=candidateStatus(c);return <article className={`person-card ${s}`} key={c.id}><strong>{c.name}</strong><span>{branchName(c.branchId)} - {vacancyName(c.vacancyId)}</span><span>Rekrutierer / Rekrutiererin: {personName(c.recruiterId)}</span><S s={s}/><div className="inline-controls"><select value={c.stage} onChange={e=>update(c.id,'stage',e.target.value)}>{candidateStages.map(x=><option key={x}>{x}</option>)}</select><input type="date" value={c.nextStepDate} onChange={e=>update(c.id,'nextStepDate',e.target.value)}/></div></article>})}{list.length===0&&<div className="empty-stage">Keine Kandidaten / Kandidatinnen</div>}</div>})}</div>}
function Coaching({items,branchName,personName,update,updateCoaching}){return <div className="coaching-board">{coachingSteps.map(step=>{const list=items.filter(x=>nextCoaching(x)===step||x.coachings?.[step]?.state==='geplant');return <div className="stage-lane" key={step}><div className="kanban-title small">{step}<span>{list.length}</span></div>{list.map(t=>{const s=traineeStatus(t), c=t.coachings[step];return <article className={`mini-person ${s}`} key={t.id}><strong>{t.name}</strong><small>{branchName(t.branchId)} - {t.role}</small><small>Ausbildner / Ausbildnerin: {personName(t.trainerId)}</small><S s={s}/><div className="inline-controls"><select value={c.state} onChange={e=>updateCoaching(t.id,step,'state',e.target.value)}>{stepStates.map(x=><option key={x}>{x}</option>)}</select><input type="date" value={c.date} onChange={e=>updateCoaching(t.id,step,'date',e.target.value)}/></div><select value={t.trainerId} onChange={e=>update(t.id,'trainerId',e.target.value)}>{persons.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></article>})}{list.length===0&&<div className="empty-stage">Keine Mitarbeitenden</div>}</div>})}</div>}
function Weekly({report,setReport,totals,vacancies,trainees,personName}){return <Panel title="Wochenreport" icon={<CalendarDays size={18}/>}><div className="weekly-report"><label><span>Kalenderwoche</span><input type="week" value={report.week} onChange={e=>setReport({...report,week:e.target.value})}/></label><div className="week-metrics"><div><span>Dossiers</span><strong>{totals.dossiers}</strong></div><div><span>Absagen</span><strong>{totals.rejections}</strong></div><div><span>Aktive Prozesse</span><strong>{totals.active}</strong></div><div><span>Ausbildung</span><strong>{totals.trainees}</strong></div></div><Mini title="Vakanzen nach Rekrutierer / Rekrutiererin" rows={countBy(vacancies,'recruiterId',personName)}/><Mini title="Coachings offen / überfällig nach Ausbildner / Ausbildnerin" rows={openCoachings(trainees,personName)}/><label><span>Bemerkung</span><textarea value={report.comment} onChange={e=>setReport({...report,comment:e.target.value})} rows="5"/></label></div></Panel>}
function VacancyForm({f,setF,submit}){return <form className="entry-form" onSubmit={submit}><Sel label="Filiale" value={f.branchId} onChange={v=>setF({...f,branchId:v})} opts={branches.map(x=>[x.id,x.name])}/><Sel label="Vakanztyp" value={f.type} onChange={v=>setF({...f,type:v})} opts={vacancyTypes.map(x=>[x,x])}/><Sel label="Rekrutierer / Rekrutiererin" value={f.recruiterId} onChange={v=>setF({...f,recruiterId:v})} opts={persons.map(x=>[x.id,x.name])}/><label><span>Nächster Schritt</span><input type="date" value={f.nextStepDate} onChange={e=>setF({...f,nextStepDate:e.target.value})}/></label><button className="primary-button">Hinzufügen</button></form>}
function VacancyTable({items,update,branchName,personName}){return <div className="table-wrap"><table><thead><tr>{['Filiale','Vakanztyp','Rekrutierer / Rekrutiererin','Status','Nächster Schritt','Dossiers','Absagen','Interviews','Probetage','Anstellungsprozess','Bemerkung'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.map(v=>{const s=vacancyStatus(v);return <tr key={v.id}><td>{branchName(v.branchId)}</td><td><select value={v.type} onChange={e=>update(v.id,'type',e.target.value)}>{vacancyTypes.map(x=><option key={x}>{x}</option>)}</select></td><td><select value={v.recruiterId} onChange={e=>update(v.id,'recruiterId',e.target.value)}>{persons.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></td><td><S s={s}/></td><td><input type="date" value={v.nextStepDate} onChange={e=>update(v.id,'nextStepDate',e.target.value)}/></td>{['dossiers','rejections','interviews','trialDays','hiring'].map(k=><td key={k}><input className="number-input" type="number" min="0" value={v[k]} onChange={e=>update(v.id,k,e.target.value)}/></td>)}<td><input value={v.notes} onChange={e=>update(v.id,'notes',e.target.value)}/></td></tr>})}</tbody></table></div>}
function CandidateForm({f,setF,submit,vacancies,branchName}){return <form className="stack-form" onSubmit={submit}><h3>Kandidat / Kandidatin erfassen</h3><label><span>Name</span><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label><span>Vakanz</span><select value={f.vacancyId} onChange={e=>{const v=vacancies.find(x=>x.id===e.target.value);setF({...f,vacancyId:e.target.value,branchId:v?.branchId||f.branchId,recruiterId:v?.recruiterId||f.recruiterId})}}>{vacancies.map(v=><option key={v.id} value={v.id}>{branchName(v.branchId)} - {v.type}</option>)}</select></label><div className="form-row"><Sel label="Status" value={f.stage} onChange={v=>setF({...f,stage:v})} opts={candidateStages.map(x=>[x,x])}/><label><span>Nächster Schritt</span><input type="date" value={f.nextStepDate} onChange={e=>setF({...f,nextStepDate:e.target.value})}/></label></div><label><span>Bemerkung</span><input value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><button className="primary-button">Kandidat / Kandidatin hinzufügen</button></form>}
function TraineeForm({f,setF,submit}){return <form className="stack-form" onSubmit={submit}><h3>Mitarbeiter / Mitarbeiterin in Ausbildung erfassen</h3><label><span>Name</span><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><Sel label="Filiale" value={f.branchId} onChange={v=>setF({...f,branchId:v})} opts={branches.map(x=>[x.id,x.name])}/><div className="form-row"><label><span>Funktion</span><input value={f.role} onChange={e=>setF({...f,role:e.target.value})}/></label><label><span>Eintrittsdatum</span><input type="date" value={f.startDate} onChange={e=>setF({...f,startDate:e.target.value})}/></label></div><Sel label="Ausbildner / Ausbildnerin" value={f.trainerId} onChange={v=>setF({...f,trainerId:v})} opts={persons.map(x=>[x.id,x.name])}/><label><span>Bemerkung</span><input value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><button className="primary-button">Ausbildung hinzufügen</button></form>}
function Branches({vacancies,trainees,filters,personName}){return <div className="branch-grid">{branches.filter(b=>filters.branchId==='all'||filters.branchId===b.id).map(b=>{const v=vacancies.filter(x=>x.branchId===b.id), t=trainees.filter(x=>x.branchId===b.id), s=branchStatus(v,t); if(filters.status!=='all'&&filters.status!==s)return null; return <article className={`branch-card ${s}`} key={b.id}><strong>{b.name}</strong><S s={s}/><div className="branch-metrics"><span><b>{v.length}</b> Vakanzen</span><span><b>{sum(v,'dossiers')}</b> Dossiers</span><span><b>{sum(v,'interviews')+sum(v,'trialDays')+sum(v,'hiring')}</b> Prozesse</span><span><b>{t.length}</b> Ausbildung</span></div>{v.slice(0,2).map(x=><small key={x.id}>{x.type}: {personName(x.recruiterId)}</small>)}</article>})}</div>}
function countBy(items,field,label){return persons.map(p=>[label(p.id),items.filter(x=>x[field]===p.id).length]).filter(x=>x[1]>0)} function sumBy(items,g,s,label){return persons.map(p=>[label(p.id),items.filter(x=>x[g]===p.id).reduce((n,x)=>n+Number(x[s]),0)]).filter(x=>x[1]>0)} function openCoachings(items,label){return persons.map(p=>[label(p.id),items.filter(x=>x.trainerId===p.id).reduce((n,t)=>n+Object.values(t.coachings).filter(c=>c.state!=='erledigt'&&(!c.date||isPast(c.date))).length,0)]).filter(x=>x[1]>0)}
createRoot(document.getElementById('root')).render(<App/>);
